homework_10/comparator/comparator/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("items/", include("items.urls")),
    path("auth/", include("myauth.urls")),
]

if settings.DEBUG:
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

homework_10/comparator/items/urls.py
from django.urls import path

from .views import (
    ItemsListView,
    ItemDetailView,
    ItemCreateView
)

app_name = "items"

urlpatterns = [
    path("", ItemsListView.as_view(), name="index"),
    path("create/", ItemCreateView.as_view(), name="create"),
    path("<int:pk>/", ItemDetailView.as_view(), name="details"),
]

homework_10/comparator/myauth/urls.py
from django.urls import path

from .views import (
    MeView,
    LoginView,
    LogoutView,
    UserCreationView,
)

app_name = "myauth"

urlpatterns = [
    path("me/", MeView.as_view(), name="me"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreationView.as_view(), name="register"),
]

homework_10/comparator/items/models.py
from typing import TYPE_CHECKING

from django.db import models


class Item(models.Model):
    name = models.CharField(max_length=64)
    url = models.TextField(blank=True, null=False)
    description = models.TextField(blank=True, null=False)
    price = models.FloatField(blank=True, null=True)

    if TYPE_CHECKING:
        objects: models.Manager

    def __str__(self):
        return self.name

homework_10/comparator/myauth/models.py
from typing import TYPE_CHECKING

from django.contrib.auth import get_user_model
from django.db import models

from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver


UserModel: AbstractUser = get_user_model()


class UserProfile(models.Model):
    user = models.OneToOneField(UserModel, on_delete=models.CASCADE, related_name="profile")
    email = models.TextField(blank=True)

    if TYPE_CHECKING:
        objects: models.Manager


@receiver(signal=post_save, sender=UserModel)
def user_saved_hadler(instance: UserModel, created: bool, **kwargs):
    if not created:
        return

    UserProfile.objects.create(user=instance)

homework_10/comparator/items/forms.py
from django.forms import ModelForm, CharField
from django.forms.widgets import Widget
from .models import Item


class ItemCreateForm(ModelForm):
    class Meta:
        model = Item
        fields = "name", "url", "description", "price"

    name = CharField(max_length=20, label="Item name")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            print(name, field, field.widget)
            widget: Widget = field.widget
            widget.attrs["class"] = "form-control"

homework_10/comparator/myauth/forms.py
from django.contrib.auth.forms import (
    AuthenticationForm as AuthenticationFormGeneric,
    UserCreationForm as UserCreationFormGeneric,
)
from django.forms import Widget
from .models import UserModel


class FormStylesMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            print(name, field, field.widget)
            widget: Widget = field.widget
            widget.attrs["class"] = "form-control"

class UserCreationForm(FormStylesMixin, UserCreationFormGeneric):

    class Meta:
        model = UserModel
        fields = "username", "email", "password1", "password2"


class AuthenticationForm(FormStylesMixin, AuthenticationFormGeneric):
    pass

homework_10/comparator/items/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
)

from .forms import ItemCreateForm
from .models import Item
# from .tasks import parse


class ItemsListView(ListView):
    template_name = "items/index.html"
    context_object_name = "items"
    queryset = (
        Item
        .objects
        # .select_related("market")
        # .prefetch_related("label")
        .order_by("pk")
        .all()
    )


class ItemCreateView(LoginRequiredMixin, CreateView):
    model = Item
    form_class = ItemCreateForm

    def get_success_url(self):
        return reverse("items:details", kwargs={"pk": self.object.pk})


class ItemDetailView(DetailView):
    template_name = "items/details.html"
    context_object_name = "item"
    queryset = (
        Item
        .objects
        # .select_related("market")
        # .prefetch_related("label")
    )

homework_10/comparator/myauth/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render

from django.contrib.auth.views import (
    LoginView as LoginViewGeneric,
    LogoutView as LogoutViewGeneric,
)
from django.views.generic import TemplateView, CreateView
from django.urls import reverse_lazy

from .models import UserModel
from .forms import AuthenticationForm, UserCreationForm


class MeView(TemplateView):
    template_name = "myauth/me.html"


class UserCreationView(CreateView):
    model = UserModel
    form_class = UserCreationForm
    success_url = reverse_lazy("myauth:me")
    template_name = "registration/register.html"

    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password2"]
        user = authenticate(self.request, username=username, password=password)
        login(self.request, user=user)
        return response


class LoginView(LoginViewGeneric):
    form_class = AuthenticationForm
    next_page = reverse_lazy("myauth:me")


class LogoutView(LogoutViewGeneric):
    next_page = reverse_lazy("myauth:me")

homework_10/comparator/items/templates/items/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
          crossorigin="anonymous">
</head>
<body>

<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Comparator</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'items:index' %}">Items</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myauth:me' %}">Me</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myauth:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myauth:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myauth:login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% block body %}
        <h1>Hello, world!</h1>
    {% endblock %}
</div>
</body>
</html>

homework_10/comparator/items/templates/items/details.html
{% extends 'items/base.html' %}

{% block title %}
    {{ item.name }} details
{% endblock %}

{% block body %}
    <h1>Item <strong>{{ item.name }}</strong></h1>
    <div>
        <p><strong>Description</strong>: {{ item.description }}</p>
        <p><strong>Price</strong>: {{ item.price }}</p>
    </div>
    <a href="{% url 'items:index' %}">Back to items list</a>
{% endblock %}

homework_10/comparator/items/templates/items/index.html
{% extends 'items/base.html' %}

{% block title %}
    Items list
{% endblock %}

{% block body %}
    <h1>Items list</h1>
    <ul class="list-group">
        {% for item in items %}
            <li class="list-group-item">
                <a href="{% url 'items:details' item.pk %}">
                    {{ item.name }}
                </a>
            </li>
        {% endfor %}
    </ul>

    <div class="my-2">
        <a
                class="btn btn-outline-info"
                href="{% url 'items:create' %}">
            Create item
        </a>
    </div>

{% endblock %}

homework_10/comparator/items/templates/items/item_form.html
{% extends 'items/base.html' %}

{% block title %}
    Create item
{% endblock %}

{% block body %}
    <h1>Create item</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button
                class="btn btn-success"
                type="submit">
            Create
        </button>
    </form>
{% endblock %}

homework_10/comparator/myauth/templates/myauth/me.html
{% extends 'items/base.html' %}

{% block title %}
    User info
{% endblock %}

{% block body %}
    <h1>Hello {% firstof user.first_name user.email user.username user %}</h1>
    <h3>email:</h3>
    <p>
        {% if user.profile.email %}
            {{ user.profile.email }}
        {% else %}
            <span>no email</span>
        {% endif %}
    </p>
{% endblock %}